apiVersion: v1
kind: Namespace
metadata:
  name: cm-interview
  labels:
    app: interview-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-app
  namespace: cm-interview
spec:
  replicas: 2
  selector:
    matchLabels:
      app: interview-app
  template:
    metadata:
      labels:
        app: interview-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: interview-app
          image: ghcr.io/yanirain/cm-interview:v1.0.0
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          ports:
            - containerPort: 5678
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: interview-app
  namespace: cm-interview
  labels:
    app: interview-app
spec:
  selector:
    app: interview-app
  ports:
    - port: 8080
      targetPort: 5678